package test;

import java.text.MessageFormat;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * AUTO-GENERATED from schema file with i18n-maven-plugin.
 * Please do not edit this file manually!
 */

public class Messages {
	private static String BASE_NAME = "messages";
	/**
	 * Example: "Question"
	 */
	public static final String question$ = "question";

	/**
	 * Example: "Question"
	 */
	public static String question$(Locale locale) {
		return Messages.translate(locale, question$);
	}

	/**
	 * If the user chooses this action, then there should be a reminder next week.
	 */
	public static class dialog {
		/**
		 * Will be asked when online update is available.
		 * 
		 * Example: "${question}: Do you really want to update?"
		 */
		public static final String confirm_update$ = "dialog.confirm_update";

		/**
		 * Will be asked when online update is available.
		 * 
		 * Example: "${question}: Do you really want to update?"
		 */
		public static String confirm_update$(Locale locale) {
			return Messages.translate(locale, confirm_update$);
		}
		/**
		 * If the user chooses this action, then there should be a reminder next week.
		 * 
		 * Example: "Erinnere mich nächste Woche!"
		 */
		public static final String next_week$ = "dialog.next_week";

		/**
		 * If the user chooses this action, then there should be a reminder next week.
		 * 
		 * Example: "Erinnere mich nächste Woche!"
		 */
		public static String next_week$(Locale locale) {
			return Messages.translate(locale, next_week$);
		}
	}
	public static String translate(Locale locale, String key, Object... params) {
		ResourceBundle bundle = ResourceBundle.getBundle(BASE_NAME, locale);
		String pattern = bundle.getString(key);
		return (new MessageFormat(pattern, locale)).format(params);
	}
}
