package test;

import java.text.MessageFormat;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * AUTO-GENERATED from schema file with i18n-maven-plugin.
 * Please do not edit this file manually!
 */

public class Messages {
	private static String BASE_NAME = "messages";

	public static class form {

		public static class validation {
			/**
			 * Example: "Validation Error"
			 */
			public static final String error$ = "form.validation.error";

			/**
			 * Example: "Validation Error"
			 */
			public static String error$(Locale locale) {
				return Messages.translate(locale, error$);
			}

			public static class error {
				/**
				 * Example: "Please check the ${form.validation.error} before submitting the form."
				 */
				public static final String summary$ = "form.validation.error.summary";

				/**
				 * Example: "Please check the ${form.validation.error} before submitting the form."
				 */
				public static String summary$(Locale locale) {
					return Messages.translate(locale, summary$);
				}
			}
			/**
			 * Example: "Field is required."
			 */
			public static final String required$ = "form.validation.required";

			/**
			 * Example: "Field is required."
			 */
			public static String required$(Locale locale) {
				return Messages.translate(locale, required$);
			}
			/**
			 * Example: "This not a valid email address."
			 */
			public static final String email$ = "form.validation.email";

			/**
			 * Example: "This not a valid email address."
			 */
			public static String email$(Locale locale) {
				return Messages.translate(locale, email$);
			}
			/**
			 * Example: "This not a valid url."
			 */
			public static final String url$ = "form.validation.url";

			/**
			 * Example: "This not a valid url."
			 */
			public static String url$(Locale locale) {
				return Messages.translate(locale, url$);
			}
		}
	}
	public static String translate(Locale locale, String key, Object... params) {
		ResourceBundle bundle = ResourceBundle.getBundle(BASE_NAME, locale);
		String pattern = bundle.getString(key);
		return (new MessageFormat(pattern, locale)).format(params);
	}
}
