/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: de, Fallback: en. Please do not edit this file manually! */

var i18n = {
  "question$" : "Frage",
  "dialog" : {
    "confirm_update$" : "Frage: Möchten Sie wirklich updaten?",
    "next_week$" : "Erinnere mich nächste Woche!"
  }
}