/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: fr, Fallback: de. Please do not edit this file manually! */

var i18n = {"question$":"Question","dialog":{"confirm_update$":"Frage: Möchten Sie wirklich updaten?","next_week$":"Erinnere mich nächste Woche!"},"yes$":"oui","no$":"non"};