/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: en. Please do not edit this file manually! */

var i18n = {
  "form" : {
    "validation" : {
      "error$" : "Validation Error",
      "error" : {
        "summary$" : "Please check the Validation Error before submitting the form."
      },
      "required$" : "Field is required.",
      "email$" : "This not a valid email address.",
      "url$" : "This not a valid url."
    }
  }
};