/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: en. Please do not edit this file manually! */

var i18n = {"question$":"Question","dialog":{"confirm_update$":"Question: Do you really want to update?","next_week$":"Remind me next week!"},"yes$":"yes","no$":"no"};