/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: fr, Fallback: de. Please do not edit this file manually! */

var i18n = {
  "form" : {
    "validation" : {
      "error$" : "Erreur de Validation",
      "error" : {
        "summary$" : "Veuillez vérifier le Erreur de Validation avant de soumettre le formulaire."
      },
      "required$" : "C'est un champ obligatoire.",
      "email$" : "Ce n'est pas une adresse email valide.",
      "url$" : "Ce n'est pas une URL valide."
    }
  }
};