/* AUTO-GENERATED from schema file [i18n] with i18n-maven-plugin. Localization: de, Fallback: en. Please do not edit this file manually! */

var i18n = {
  "form" : {
    "validation" : {
      "error$" : "Validierungsfehler",
      "error" : {
        "summary$" : "Bitte prüfe den Validierungsfehler vor dem Absenden des Formulars."
      },
      "required$" : "Das ist ein Pflichtfeld.",
      "email$" : "Das ist keine gültige E-Mail Adresse.",
      "url$" : "Das ist keine gültige URL."
    }
  }
};